
# -------------------------------------------------------------
# Code_executor_agent.py
#
# This file defines the CodeExecutorAgent used in the agent team.
# The agent is responsible for executing Python code (usually generated by other agents)
# in a safe, isolated environment (such as Docker).
# It handles code execution, error reporting, and output delivery.
# -------------------------------------------------------------

from autogen_agentchat.agents import CodeExecutorAgent

# Factory function to create and return a CodeExecutorAgent instance
# code_executor: The object responsible for running code (e.g., Docker executor)
def getCodeExecutorAgent(code_executor):

    # Create the CodeExecutorAgent with a specific name and executor
    code_executor_agent = CodeExecutorAgent(
        name='Python_Code_Executor',
        code_executor=code_executor
    )

    # Return the agent instance to be used in the agent team
    return code_executor_agent